name: doc_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  bloc: ^8.1.3
  build_runner: ^2.4.8
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.4.1
  easy_localization: ^3.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: null
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.7.0
  get_it: ^7.6.7
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.1
  mockito: ^5.4.4
  persistent_bottom_nav_bar: ^5.0.2
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/png/
    - assets/images/svg/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Black.ttf
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-ExtraLight.ttf
        - asset: assets/fonts/Inter-ExtraLight.ttf
        - asset: assets/fonts/Inter-Light.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
        - asset: assets/fonts/Inter-Thin.ttf
flutter_intl:
  enabled: true
